# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7ca95e9ad04c921f528d555ea0f1b028a1ec4694f6a39dcaf858cf9931592abddd97584fd810ca4c5317065884a30f8153dfc91d87c027cbea1acd5028a82e

test:
  secret_key_base: b32a6516874b4b2ab9b4a30ed87e7de616663f7ae2ab5b1db97d7998a64e09bfbd05d09e5dd0a2af75b562903fe99f300497e18fc321909bd3863e63fc3dc991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
